### ISSUE TITLE
-215:Assertion failed

### ISSUE THREAD

**Issue by KeksTheAllmighty** [Lime365/wow-fishbot#1]
![d3](https://user-images.githubusercontent.com/68150167/149952210-4eb08a0d-73a1-4ecd-9503-d5e4035e9de8.png)

So when I am using this image, I am getting:

```
Session:
Fished for 0s
Bobbers clicked: 0
Lures used: 0
Timeouts: 0
Throwing...
Traceback (most recent call last):
  File "fish.py", line 246, in <module>
    bobber_info = find_bobber(screen_region(window, monitor), bobber_img, bobber_mask)
  File "fish.py", line 145, in find_bobber
    match = cv2.matchTemplate(source, bobber, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'matchTemplate'
```

I was checking the types and of the images in the find_bobber function and they both appeared to be uint8, i assume somehow there is a wrong type...

**Comment by Lime365** [comment]
Hi @KeksTheAllmighty,
Sorry for the (very) late reply.
I've never gotten that error before, is that image one of the examples provided in the repo?
I'd recommend when you find your spot to fish you cast the bobber once manually and take a screenshot of the bobber (i use greenshot). Save it in the repo folder, and pass that as an argument to `bobber_img`
I just fired this up again on my laptop after i started playing again and still works like a charm. (Only need to install python and install some packages with Pip. Knowing more now i will create a requirements.txt for this process and update the repo)

**Comment by KeksTheAllmighty** [comment]
Hey, whalecum back :)
Are you playing on windows or linux? I will try it again later and tell you if the issue persists.

**Comment by Lime365** [comment]
Thanks! Wow didn't expect an answer so fast :smile: 
Mb forgot to say, I've only run this on Windows 10! Not tested with any other OS.

**Comment by cfvphxzx762** [comment]
> 谢谢！哇没想到回复这么快😄 Mb忘记了说，我只在Windows 10上运行过！未经任何其他操作系统测试。

Hey, first of all, thank you very much for sharing. I also encountered the same problem. It happened when I used the screenshot function (shift+windows+s) that comes with windows. After I changed other screenshots, it can be used normally.

Here's a simple suggestion. You can add a bit of random delay at fishing/capture nodes, which can help users avoid Banned!

Thank you again.
